services:
  nvidia-test:
    image: tensorflow/tensorflow:2.15.0-gpu
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
