services:
  ai-delver-intelligence:
    image: ai-delver-intelligence
    container_name: ai-delver-intelligence
    build:
      context: .
      dockerfile: ai-delver-intelligence/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8001:8001"
    working_dir: /app
    volumes:
      - ./ai-delver-intelligence:/app
      - ./pytiling-lib:/app/pytiling-lib
      - ./pyglet-dragonbones-lib:/app/pyglet-dragonbones-lib
      - ./ai-delver-runtime:/app/ai-delver-runtime
      - ./ai-delver-level:/app/ai-delver-level
      - ./assets:/app/assets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python3", "src/main.py"]
    stdin_open: true
    tty: true